#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
#  Configuration file for "BlockSaver". #
#  @author Nikita Pekin (Indivisible0)  #
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#


#======== Settings ==========#

## The name of the effect to be played when a player fails to damage a reinforced block.
# Note: please use an effect contained within the Effect class.
# Default: EXTINGUISH
reinforcementDamageFailEffect: EXTINGUISH

## The name of the effect to be played when a player successfully damages a reinforced block.
# Notes:
#   Please use an effect contained within the Effect class.
#   This value can be overriden by the useParticleEffects option, which, if enabled, will instead use coloured particle effects to represent the state of the block as it is damaged or reinforced.
# Default: POTION_BREAK
reinforcementDamageSuccessEffect: POTION_BREAK

## The name of the sound to be played when a player reinforces a block.
# Note: please use a sound contained within the Sound class.
# Default: ANVIL_USE
reinforceSuccessSound: ANVIL_USE

## The name of the sound to be played when a player fails to reinforce a block.
# Note: please use a sound contained within the Sound class.
# Default: BLAZE_HIT
reinforceFailSound: BLAZE_HIT

## The name of the sound to be played when a player fails to hit a reinforced block.
# Note: please use a sound contained within the Sound class.
# Default: CREEPER_DEATH
hitFailSound: CREEPER_DEATH

## Whether or not reinforcement values should accumulate indefinitely, as opposed to reaching the limits specified by the Reinforceable Blocks List.
# Notes:
#   If this is set to false, the values will be capped at those provided in the list.
#   Setting this to true then reverting to false will not reset the values to their maximums as defined in the Reinforceable Blocks List.
# Default: true
accumulateReinforcementValues: true

## Whether or not TNT can damage reinforced blocks.
# Note: one TNT blast will only decrement the reinforcement value by one.
# Default: true
tntDamagesReinforcedBlocks: true

## Whether or not liquids can destroy reinforced blocks which can wash away (e.g. torches, railroad tracks).
# Default: true
liquidsDestroyReinforcedBlocks: true

## Whether or not fire can damage reinforced blocks.
# Note: if this is set to true, it is recommended to set extinguishReinforcementFire to true, otherwise fire will burn indefinitely and destroy enchantments quickly.
# Default: true
fireDamagesReinforcedBlocks: true

## Whether or not fires burning on reinforced blocks should occaisionally extinguish, in order to prevent these blocks from being entirely ravaged by a fire.
# Default: true
extinguishReinforcementFire: true

## If extinguishReinforcementFire is set to true, this value determines the likelyhood that a fire is to be extinguished.
# Note: This must be a value in the range 0.0-1.0, with a 1.0 being a 100% chance of extinguishment.
# Default: 0.8
extinguishChance: 0.8

## Whether or not pistons can move reinforced blocks.
# Default: true
pistonsMoveReinforcedBlocks: true

## Whether or not the plugin should attempt to use color-changing particle effects (dependant on the health of the reinforcement) for feedback rather than using the effects defined above, where possible.
# Default: true
useParticleEffects: true

## Whether or not blocks should be allowed to "fade" while reinforced (e.g. snow melting, ice melting).
# Default: true
allowBlockFading: true

## Whether or not the creator of the reinforcement should be given a grace period to remove the reinforcement if it is in an undesirable location.
# Note: the item used in the reinforcement is not refunded.
# Default: true
allowReinforcementGracePeriod: true

## The amount of time the grace period should last to remove a reinforcement, if allowReinforcementGracePeriod is set to true.
# Note: must be an integer value greater than zero. The value is measured in seconds.
# Default: 3
gracePeriodTime: 3

## Whether or not reinforcements should "heal" to their maximum reinforcement after a period of time.
# Note: this does not mean the maximum reinforcement as described in the Reinforceable Blocks List, but rather the last highest reinforcement the block was raised to, prior to attack.
# Default: true
allowReinforcementHealing: true

## The amount of time before a block "heals" its reinforcement, if allowReinforcementHealing is set to true.
# Note: must be a value greater than zero. The value is measured in seconds.
# Default: 5
reinforcementHealTime: 5


#======== Reinforceable Blocks List ========#

## A list of all the items which can be reinforced by this plugin, and the maximum "reinforcement value" the block can reach, if accumulateReinforcementValues is set to false.
# (Note: Any value less than 1 is invalid)
reinforceableBlocks:
  DIAMOND_BLOCK: 6
  DOUBLE_STEP: 6
  GLASS: 1
  GLOWSTONE: 1
  GOLD_BLOCK: 6
  GRASS: 4
  ICE: 1
  IRON_BLOCK: 6
  LAPIS_BLOCK: 6
  LOG: 4
  NETHER_BRICK: 15
  NETHER_BRICK_STAIRS: 5
  PISTON_BASE: 2
  PISTON_EXTENSION: 2
  PISTON_STICKY_BASE: 2
  SAND: 3
  SANDSTONE: 5
  SANDSTONE_STAIRS: 5
  SMOOTH_BRICK: 15
  SMOOTH_STAIRS: 5
  STEP: 3
  STONE: 5
  THIN_GLASS: 1
  WOOD: 2
  WOOD_DOUBLE_STEP: 2
  WOOD_STAIRS: 2
  WOOD_STEP: 1
  WOOL: 1


#======== Reinforcement Item List ========#

## A list of all the items which can be used to reinforce blocks, and their corresponding reinforcement values.
# Notes:
#   Setting a value of -2 will mean the reinforcement will automatically be the maximum value the block can take.
#   Any other value less than 1 is invalid.
#   If "accumulateReinforcementValues" is set to true, any material set here with a reinforcement value of -2 will not reinforce blocks.
reinforcementBlocks:
  OBSIDIAN: -2
  IRON_INGOT: 1
  GOLD_INGOT: 3
  DIAMOND: 10


#======== Tool Requirement List ========#

## A list of tools which can break certain blocks when reinforced. Used to prevent un-advanced players from easily destroying reinforcements.
toolRequirements:
  DIAMOND_BLOCK: DIAMOND_PICKAXE
  DOUBLE_STEP: DIAMOND_PICKAXE
  GLASS: DIAMOND_PICKAXE
  GLOWSTONE: DIAMOND_PICKAXE
  GOLD_BLOCK: DIAMOND_PICKAXE
  GRASS: DIAMOND_SPADE,DIAMOND_PICKAXE
  ICE: DIAMOND_PICKAXE
  IRON_BLOCK: DIAMOND_PICKAXE
  LAPIS_BLOCK: DIAMOND_PICKAXE
  LOG: DIAMOND_AXE
  NETHER_BRICK: DIAMOND_PICKAXE
  NETHER_BRICK_STAIRS: DIAMOND_PICKAXE
  PISTON_BASE: DIAMOND_PICKAXE
  PISTON_EXTENSION: DIAMOND_PICKAXE
  PISTON_STICKY_BASE: DIAMOND_PICKAXE
  SAND: DIAMOND_SPADE
  SANDSTONE: DIAMOND_PICKAXE
  SANDSTONE_STAIRS: DIAMOND_PICKAXE
  SMOOTH_BRICK: DIAMOND_PICKAXE
  SMOOTH_STAIRS: DIAMOND_PICKAXE
  STEP: DIAMOND_PICKAXE
  STONE: DIAMOND_PICKAXE
  THIN_GLASS: DIAMOND_PICKAXE
  WOOD: DIAMOND_AXE
  WOOD_DOUBLE_STEP: DIAMOND_AXE
  WOOD_STAIRS: DIAMOND_AXE
  WOOD_STEP: DIAMOND_AXE
