#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
#  Configuration file for "BlockSaver". #
#  @author Nikita Pekin (Indivisible0)  #
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#


#======== Feedback ==========#

## The name of the effect to be played when a player fails to damage a reinforced block.
# Note: please use an effect contained within the Effect class.
# Default: EXTINGUISH
reinforcementDamageFailEffect: EXTINGUISH

## The name of the sound to be played when a player reinforces a block.
# Note: please use a sound contained within the Sound class.
# Default: ANVIL_USE
reinforceSuccessSound: ANVIL_USE

## The name of the sound to be played when a player fails to reinforce a block.
# Note: please use a sound contained within the Sound class.
# Default: BLAZE_HIT
reinforceFailSound: BLAZE_HIT

## The name of the sound to be played when a player fails to hit a reinforced block.
# Note: please use a sound contained within the Sound class.
# Default: CREEPER_DEATH
hitFailSound: CREEPER_DEATH


#======== Functionality ========#

## Whether or not TNT can damage reinforced blocks.
# Default: true
tntDamagesReinforcedBlocks: true

## Whether or not TNT entirely strips reinforcements or decrements them.
# Note: this option is ignored if tntDamagesReinforcedBlocks is set to false.
# Default: false
tntStripReinforcementEntirely: false

## Whether or not liquids can destroy reinforced blocks which can wash away (e.g. torches, railroad tracks).
# Default: true
liquidsDestroyReinforcedBlocks: true

## Whether or not physics-affected blocks (i.e. sand and gravel), if reinforced, are allowed to fall down.
# Note: if the blocks are allowed to fall, their reinforcement is simply removed, not transferred to their new location.
# Default: true
allowReinforcedBlockPhysics: true

## Whether or not fire can damage reinforced blocks.
# Note: if this is set to true, it is recommended to set extinguishReinforcementFire to true, otherwise fire will burn indefinitely and destroy enchantments quickly.
# Default: true
fireDamagesReinforcedBlocks: true

## Whether or not fires burning on reinforced blocks should occasionally extinguish, in order to prevent these blocks from being entirely ravaged by a fire.
# Default: true
extinguishReinforcementFire: true

## If extinguishReinforcementFire is set to true, this value determines the likelihood that a fire is to be extinguished.
# Note: This must be a value in the range 0.0-1.0, with a 1.0 being a 100% chance of extinguishing.
# Default: 0.9
extinguishChance: 0.9

## Whether or not pistons can move reinforced blocks.
# Default: true
pistonsMoveReinforcedBlocks: true

## Whether or not blocks should be allowed to "fade" while reinforced (e.g. snow melting, ice melting).
# Default: false
allowBlockFading: false

## The amount of time the grace period should last to remove a reinforcement, if allowReinforcementGracePeriod is set to true.
# Note: must be an integer value greater than zero. The value is measured in seconds.
# Default: 3
gracePeriodTime: 3

## The amount of time before a block "heals" its reinforcement, if allowReinforcementHealing is set to true.
# Note: must be a value greater than zero. The value is measured in seconds.
# Default: 5
reinforcementHealingTime: 5

## Whether or not a block remains in place when its RV reaches 0.
# Note: if this is set to true, when RV reaches 0, the reinforcement is simply removed. Otherwise, the block gets destroyed.
# Default: false
leaveBlockAfterDeinforce: false

## Whether or not mobs can change/damage reinforced blocks.
# Notes:
#   Setting this to false will mean sheep cannot eat reinforced grass.
#   Endermen will be unable to pickup reinforced blocks.
#   Withers will be unable to damage reinforced blocks.
# Default: false
mobsInteractWithReinforcedBlocks: false

## Whether or not the enderdragon can change/damage reinforced blocks.
# Default: false
enderdragonInteractWithReinforcedBlocks: false


#======== Worlds ========#

## List of worlds protected by BlockSaver.
worlds:
  - world
  - world_nether


#======== Advanced ========#

## Whether or not to log BlockSaver events into Prism.
# Default: true
prismLogging: true

## Whether or not to log BlockSaver events into Insight.
# Default: true
insightLogging: true

## Whether or not to integrate BlockSaver into WorldEdit.
# Default: true
integrateWorldEdit: true


#======== Reinforcement Item List ========#

## A list of all the items which can be used to reinforce blocks, and the number of times they may be used.
reinforcementBlocks:
  OBSIDIAN: 8


#======== Reinforceable Blocks List ========#

## A list of all the items which can be reinforced by this plugin, and the maximum "reinforcement value" the block can reach, if accumulateReinforcementValues is set to false.
# Note: Any value less than 1 is invalid
reinforceableBlocks:
  STONE: 48
  GRASS: 95
  DIRT: 95
  COBBLESTONE: 39
  WOOD: 39
  GOLD_ORE: 17
  IRON_ORE: 17
  COAL_ORE: 25
  LOG: 39
  LEAVES: 189
  SPONGE: 12
  GLASS: 22
  LAPIS_ORE: 17
  LAPIS_BLOCK: 17
  DISPENSER: 22
  SANDSTONE: 95
  NOTE_BLOCK: 95
  BED_BLOCK: 33
  POWERED_RAIL: 95
  DETECTOR_RAIL: 95
  PISTON_STICKY_BASE: 14
  WEB: 25
  PISTON_BASE: 14
  PISTON_EXTENSION: 14
  WOOL: 39
  PISTON_MOVING_PIECE: 14
  GOLD_BLOCK: 17
  IRON_BLOCK: 11
  DOUBLE_STEP: 39
  STEP: 39
  BRICK: 39
  BOOKSHELF: 48
  MOSSY_COBBLESTONE: 39
  OBSIDIAN: 2
  WOOD_STAIRS: 39
  CHEST: 28
  DIAMOND_ORE: 17
  DIAMOND_BLOCK: 11
  WORKBENCH: 28
  SOIL: 95
  FURNACE: 22
  BURNING_FURNACE: 22
  SIGN_POST: 64
  WOODEN_DOOR: 25
  LADDER: 17
  RAILS: 95
  COBBLESTONE_STAIRS: 39
  WALL_SIGN: 64
  LEVER: 14
  STONE_PLATE: 95
  IRON_DOOR_BLOCK: 16
  WOOD_PLATE: 95
  REDSTONE_ORE: 17
  GLOWING_REDSTONE_ORE: 17
  STONE_BUTTON: 14
  ICE: 95
  SNOW_BLOCK: 189
  CACTUS: 17
  CLAY: 95
  JUKEBOX: 39
  FENCE: 39
  NETHERRACK: 189
  SOUL_SAND: 95
  GLOWSTONE: 22
  JACK_O_LANTERN: 64
  TRAP_DOOR: 25
  SMOOTH_BRICK: 48
  HUGE_MUSHROOM_1: 189
  HUGE_MUSHROOM_2: 189
  IRON_FENCE: 16
  THIN_GLASS: 22
  FENCE_GATE: 39
  BRICK_STAIRS: 39
  SMOOTH_STAIRS: 48
  MYCEL: 95
  NETHER_BRICK: 39
  NETHER_FENCE: 39
  NETHER_BRICK_STAIRS: 39
  ENCHANTMENT_TABLE: 16
  BREWING_STAND: 95
  CAULDRON: 39
  ENDER_STONE: 25
  REDSTONE_LAMP_OFF: 22
  REDSTONE_LAMP_ON: 22
  WOOD_DOUBLE_STEP: 39
  WOOD_STEP: 39
  SANDSTONE_STAIRS: 95
  EMERALD_ORE: 17
  ENDER_CHEST: 5
  EMERALD_BLOCK: 11
  SPRUCE_WOOD_STAIRS: 39
  BIRCH_WOOD_STAIRS: 39
  JUNGLE_WOOD_STAIRS: 39
  BEACON: 4
  COBBLE_WALL: 39
  WOOD_BUTTON: 14
  SKULL: 11
  ANVIL: 16
  TRAPPED_CHEST: 28
  GOLD_PLATE: 95
  IRON_PLATE: 95
  DAYLIGHT_DETECTOR: 189
  REDSTONE_BLOCK: 16
  QUARTZ_ORE: 25
  HOPPER: 25
  QUARTZ_BLOCK: 95
  QUARTZ_STAIRS: 95
  ACTIVATOR_RAIL: 95
  DROPPER: 22
  STAINED_CLAY: 48
  HAY_BLOCK: 14
  CARPET: 64
  HARD_CLAY: 48
  COAL_BLOCK: 16


#======== Tool Requirement List ========#

## A list of tools which can break certain blocks when reinforced. Used to prevent un-advanced players from easily destroying reinforcements.
# Notes:
#   Materials must use names as defined by the Bukkit Material class.
#   If a reinforceable block does not have any tools listed, it will be unbreakable by a player (but fire and TNT may still apply).
#   Write "ALL" in order to signify that the block may be broken by any tool or block, including a player's hands.
#   Write "HANDS" to signify that the block is breakable by a player's hands, in addition to any other tool listed.
toolRequirements:
  ACTIVATOR_RAIL: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  ANVIL: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  BIRCH_WOOD_STAIRS: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  BOOKSHELF: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  BREWING_STAND: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  BRICK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  BRICK_STAIRS: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  BURNING_FURNACE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  CAULDRON: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  CHEST: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  CLAY: IRON_SPADE,DIAMOND_SPADE,GOLD_SPADE
  COBBLE_WALL: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  COBBLESTONE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  COBBLESTONE_STAIRS: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  DAYLIGHT_DETECTOR: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  DETECTOR_RAIL: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  DIAMOND_BLOCK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  DIRT: IRON_SPADE,DIAMOND_SPADE,GOLD_SPADE
  DISPENSER: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  DOUBLE_STEP: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  DROPPER: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  EMERALD_BLOCK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  ENCHANTMENT_TABLE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  ENDER_CHEST: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  ENDER_STONE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  FENCE: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  FENCE_GATE: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  FURNACE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  GOLD_BLOCK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  GRASS: IRON_SPADE,DIAMOND_SPADE,GOLD_SPADE
  HOPPER: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  ICE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  IRON_BLOCK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  IRON_DOOR: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  IRON_FENCE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  JACK_O_LANTERN: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  JUKEBOX: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  JUNGLE_WOOD_STAIRS: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  LAPIS_BLOCK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  LOG: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  MOB_SPAWNER: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  MOSSY_COBBLESTONE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  MYCEL: IRON_SPADE,DIAMOND_SPADE,GOLD_SPADE
  NETHER_BRICK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  NETHER_BRICK_STAIRS: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  NETHER_FENCE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  NETHERRACK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  NOTE_BLOCK: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  OBSIDIAN: DIAMOND_PICKAXE
  POWERED_RAIL: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  QUARTZ_BLOCK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  QUARTZ_STAIRS: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  RAILS: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  REDSTONE_BLOCK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  SANDSTONE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  SANDSTONE_STAIRS: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  SIGN: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  SIGN_POST: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  SMOOTH_BRICK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  SMOOTH_STAIRS: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  SNOW_BLOCK: IRON_SPADE,DIAMOND_SPADE,GOLD_SPADE
  SOIL: IRON_SPADE,DIAMOND_SPADE,GOLD_SPADE
  SOUL_SAND: IRON_SPADE,DIAMOND_SPADE,GOLD_SPADE
  SPRUCE_WOOD_STAIRS: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  STEP: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  STONE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  TRAP_DOOR: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  TRAPPED_CHEST: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  WALL_SIGN: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  WOOD: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  WOOD_DOOR: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  WOOD_DOUBLE_STEP: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  WOOD_STAIRS: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  WOOD_STEP: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  WORKBENCH: IRON_AXE,DIAMOND_AXE,GOLD_AXE
