#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
#  Configuration file for "BlockSaver". #
#  @author Nikita Pekin (Indivisible0)  #
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#


#======== Settings ==========#

## The name of the effect to be played when a player fails to damage a reinforced block.
# Note: please use an effect contained within the Effect class.
# Default: EXTINGUISH
reinforcementDamageFailEffect: EXTINGUISH

## The name of the effect to be played when a player successfully damages a reinforced block.
# Notes:
#   Please use an effect contained within the Effect class.
#   This value can be overriden by the useParticleEffects option, which, if enabled, will instead use coloured particle effects to represent the state of the block as it is damaged or reinforced.
# Default: POTION_BREAK
reinforcementDamageSuccessEffect: POTION_BREAK

## The name of the sound to be played when a player reinforces a block.
# Note: please use a sound contained within the Sound class.
# Default: ANVIL_USE
reinforceSuccessSound: ANVIL_USE

## The name of the sound to be played when a player fails to reinforce a block.
# Note: please use a sound contained within the Sound class.
# Default: BLAZE_HIT
reinforceFailSound: BLAZE_HIT

## The name of the sound to be played when a player fails to hit a reinforced block.
# Note: please use a sound contained within the Sound class.
# Default: CREEPER_DEATH
hitFailSound: CREEPER_DEATH

## Whether or not reinforcement values should accumulate indefinitely, as opposed to reaching the limits specified by the Reinforceable Blocks List.
# Notes:
#   If this is set to false, the values will be capped at those provided in the list.
#   Setting this to true then reverting to false will not reset the values to their maximums as defined in the Reinforceable Blocks List.
# Default: true
accumulateReinforcementValues: true

## Whether or not TNT can damage reinforced blocks.
# Default: true
tntDamagesReinforcedBlocks: true

## Whether or not TNT entirely strips reinforcements or decrements them.
# Note: this option is ignored if tntDamagesReinforcedBlocks is set to false.
# Default: true
tntStripReinforcementEntirely: true

## Whether or not liquids can destroy reinforced blocks which can wash away (e.g. torches, railroad tracks).
# Default: true
liquidsDestroyReinforcedBlocks: true

## Whether or not physics-affected blocks (i.e. sand and gravel), if reinforced, are allowed to fall down.
# Note: if the blocks are allowed to fall, their reinforcement is simply removed, not transferred to their new location.
# Default: true
allowReinforcedBlockPhysics: true

## Whether or not fire can damage reinforced blocks.
# Note: if this is set to true, it is recommended to set extinguishReinforcementFire to true, otherwise fire will burn indefinitely and destroy enchantments quickly.
# Default: true
fireDamagesReinforcedBlocks: true

## Whether or not fires burning on reinforced blocks should occaisionally extinguish, in order to prevent these blocks from being entirely ravaged by a fire.
# Default: true
extinguishReinforcementFire: true

## If extinguishReinforcementFire is set to true, this value determines the likelyhood that a fire is to be extinguished.
# Note: This must be a value in the range 0.0-1.0, with a 1.0 being a 100% chance of extinguishment.
# Default: 0.8
extinguishChance: 0.8

## Whether or not pistons can move reinforced blocks.
# Default: true
pistonsMoveReinforcedBlocks: true

## Whether or not the plugin should attempt to use color-changing particle effects (dependant on the health of the reinforcement) for feedback rather than using the effects defined above, where possible.
# Default: true
useParticleEffects: true

## Whether or not blocks should be allowed to "fade" while reinforced (e.g. snow melting, ice melting).
# Default: true
allowBlockFading: true

## Whether or not the creator of the reinforcement should be given a grace period to remove the reinforcement if it is in an undesirable location.
# Note: the item used in the reinforcement is not refunded.
# Default: true
allowReinforcementGracePeriod: true

## The amount of time the grace period should last to remove a reinforcement, if allowReinforcementGracePeriod is set to true.
# Note: must be an integer value greater than zero. The value is measured in seconds.
# Default: 3
gracePeriodTime: 3

## Whether or not reinforcements should "heal" to their maximum reinforcement after a period of time.
# Note: this does not mean the maximum reinforcement as described in the Reinforceable Blocks List, but rather the last highest reinforcement the block was raised to, prior to attack.
# Default: true
allowReinforcementHealing: true

## The amount of time before a block "heals" its reinforcement, if allowReinforcementHealing is set to true.
# Note: must be a value greater than zero. The value is measured in seconds.
# Default: 5
reinforcementHealTime: 5

## Whether or not a block remains in place when its RV reaches 0.
# Note: if this is set to true, when RV reaches 0, the reinforcement is simply removed. Otherwise, the block gets destroyed.
# Default: false
leaveBlockAfterDeinforce: false


#======== Reinforceable Blocks List ========#

## A list of all the items which can be reinforced by this plugin, and the maximum "reinforcement value" the block can reach, if accumulateReinforcementValues is set to false.
# (Note: Any value less than 1 is invalid)
reinforceableBlocks:
  STONE: 10
  OBSIDIAN: 2
  SMOOTH_BRICK: 10
  SMOOTH_STAIRS: 10
  STEP: 10
  DOUBLE_STEP: 10
  NETHER_BRICK_STAIRS: 10
  NETHER_FENCE: 10
  NETHER_BRICK: 10
  MOSSY_COBBLESTONE: 10
  COBBLESTONE: 10
  COBBLESTONE_STAIRS: 10
  COBBLE_WALL: 10
  BRICK: 10
  BRICK_STAIRS: 10
  REDSTONE_BLOCK: 7
  LAPIS_BLOCK: 7
  ENDER_STONE: 7
  GOLD_BLOCK: 7
  FURNACE: 5
  BURNING_FURNACE: 5
  DISPENSER: 5
  MOB_SPAWNER: 10
  IRON_FENCE:
  ENCHANTMENT_TABLE: 5
  IRON_BLOCK: 5
  EMERALD_BLOCK: 5
  DIAMOND_BLOCK: 5
  ANVIL: 5
  ENDER_CHEST: 5
  QUARTZ_BLOCK: 15
  QUARTZ_STAIRS: 15
  SANDSTONE: 15
  SANDSTONE_STAIRS: 15
  RAILS: 15
  ACTIVATOR_RAIL: 15
  DETECTOR_RAIL: 15
  POWERED_RAIL: 15
  NETHERRACK: 20
  BREWING_STAND: 20
  ICE: 20
  CAULDRON: 10
  HOPPER: 7
  DROPPER: 5
  IRON_DOOR: 3
  TRAP_DOOR: 3
  CHEST: 5
  TRAPPED_CHEST:
  WORKBENCH: 5
  FENCE: 5
  FENCE_GATE: 5
  WOOD: 5
  LOG: 5
  WOOD_STEP: 5
  WOOD_DOUBLE_STEP: 5
  WOOD_STAIRS: 5
  SPRUCE_WOOD_STAIRS: 5
  BIRCH_WOOD_STAIRS: 5
  JUNGLE_WOOD_STAIRS: 5
  WOOD_DOOR: 5
  BOOKSHELF: 10
  JACK_O_LANTERN: 10
  SIGN: 10
  WALL_SIGN: 10
  SIGN_POST: 10
  NOTE_BLOCK: 10
  WOOL: 10
  SOIL: 10
  SNOW_BLOCK: 10
  LEAVES: 10
  VINE: 10
  GRASS: 10
  MYCEL: 10
  DIRT: 10
  CLAY: 10
  SOUL_SAND: 10
  LADDER: 5
  JUKEBOX: 10
  DAYLIGHT_DETECTOR: 20
  TORCH: 10
  GLASS: 10
  THIN_GLASS: 10
  BEACON: 10
  FLOWER_POT: 10
  WATER_LILY: 10
  REDSTONE_WIRE: 10
  REDSTONE_TORCH_OFF: 10
  REDSTONE_TORCH_ON: 10
  REDSTONE_COMPARATOR_ON: 10
  REDSTONE_COMPARATOR_OFF: 10
  REDSTONE_LAMP_ON: 5
  REDSTONE_LAMP_OFF: 5
  DIODE_BLOCK_OFF: 10
  DIODE_BLOCK_ON: 10
  GLOWSTONE: 5
  WOOD_BUTTON: 3
  STONE_BUTTON: 3
  CACTUS: 3
  LEVER: 3


#======== Reinforcement Item List ========#

## A list of all the items which can be used to reinforce blocks, and their corresponding reinforcement values.
# Notes:
#   Setting a value of -2 will mean the reinforcement will automatically be the maximum value the block can take.
#   Any other value less than 1 is invalid.
#   If "accumulateReinforcementValues" is set to true, any material set here with a reinforcement value of -2 will not reinforce blocks.
reinforcementBlocks:
  OBSIDIAN: -2
  IRON_INGOT: 1
  GOLD_INGOT: 3
  DIAMOND: 10


#======== Tool Requirement List ========#

## A list of tools which can break certain blocks when reinforced. Used to prevent un-advanced players from easily destroying reinforcements.
toolRequirements:
  STONE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  OBSIDIAN: DIAMOND_PICKAXE
  SMOOTH_BRICK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  SMOOTH_STAIRS: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  STEP: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  DOUBLE_STEP: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  NETHER_BRICK_STAIRS: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  NETHER_FENCE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  NETHER_BRICK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  MOSSY_COBBLESTONE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  COBBLESTONE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  COBBLESTONE_STAIRS: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  COBBLE_WALL: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  BRICK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  BRICK_STAIRS: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  REDSTONE_BLOCK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  LAPIS_BLOCK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  ENDER_STONE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  GOLD_BLOCK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  FURNACE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  BURNING_FURNACE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  DISPENSER: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  MOB_SPAWNER: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  IRON_FENCE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  ENCHANTMENT_TABLE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  IRON_BLOCK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  EMERALD_BLOCK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  DIAMOND_BLOCK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  ANVIL: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  ENDER_CHEST: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  QUARTZ_BLOCK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  QUARTZ_STAIRS: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  SANDSTONE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  SANDSTONE_STAIRS: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  RAILS: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  ACTIVATOR_RAIL: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  DETECTOR_RAIL: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  POWERED_RAIL: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  NETHERRACK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  BREWING_STAND: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  ICE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  CAULDRON: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  HOPPER: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  DROPPER: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  IRON_DOOR: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  TRAP_DOOR: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  CHEST: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  TRAPPED_CHEST: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  WORKBENCH: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  FENCE: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  FENCE_GATE: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  WOOD: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  LOG: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  WOOD_STEP: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  WOOD_DOUBLE_STEP: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  WOOD_STAIRS: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  SPRUCE_WOOD_STAIRS: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  BIRCH_WOOD_STAIRS: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  JUNGLE_WOOD_STAIRS: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  WOOD_DOOR: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  BOOKSHELF: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  JACK_O_LANTERN: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  SIGN: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  WALL_SIGN: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  SIGN_POST: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  NOTE_BLOCK: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  SOIL: IRON_SPADE,DIAMOND_SPADE,GOLD_SPADE
  SNOW_BLOCK: IRON_SPADE,DIAMOND_SPADE,GOLD_SPADE
  MYCEL: IRON_SPADE,DIAMOND_SPADE,GOLD_SPADE
  DIRT: IRON_SPADE,DIAMOND_SPADE,GOLD_SPADE
  CLAY: IRON_SPADE,DIAMOND_SPADE,GOLD_SPADE
  SOUL_SAND: IRON_SPADE,DIAMOND_SPADE,GOLD_SPADE
  JUKEBOX: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  DAYLIGHT_DETECTOR: IRON_AXE,DIAMOND_AXE,GOLD_AXE
