#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
#  Configuration file for "BlockSaver". #
#  @author Nikita Pekin (Indivisible0)  #
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#


#======== Feedback ==========#

## Which feedback mode the plugin should use to represent damage being done to a reinforced block.
# Notes:
#   "visual" mode makes the plugin attempt to use color-changing particle effects (dependant on the health of the reinforcement).
#   "auditory" mode makes the plugin use auditory feedback (which changes based on the block's RV).
#   "off" mode uses the feedback defined below for damage events.
# Default: visual
primaryFeedback: true

## The name of the effect to be played when a player fails to damage a reinforced block.
# Note: please use an effect contained within the Effect class.
# Default: EXTINGUISH
reinforcementDamageFailEffect: EXTINGUISH

## The name of the effect to be played when a player successfully damages a reinforced block.
# Notes:
#   Please use an effect contained within the Effect class.
#   This value can be overridden by the useParticleEffects option, which, if enabled, will instead use coloured particle effects to represent the state of the block as it is damaged or reinforced.
# Default: POTION_BREAK
reinforcementDamageSuccessEffect: POTION_BREAK

## The name of the sound to be played when a player reinforces a block.
# Note: please use a sound contained within the Sound class.
# Default: ANVIL_USE
reinforceSuccessSound: ANVIL_USE

## The name of the sound to be played when a player fails to reinforce a block.
# Note: please use a sound contained within the Sound class.
# Default: BLAZE_HIT
reinforceFailSound: BLAZE_HIT

## The name of the sound to be played when a player fails to hit a reinforced block.
# Note: please use a sound contained within the Sound class.
# Default: CREEPER_DEATH
hitFailSound: CREEPER_DEATH


#======== Functionality ========#

## Whether or not reinforcement values should accumulate indefinitely, as opposed to reaching the limits specified by the Reinforceable Blocks List.
# Notes:
#   If this is set to false, the values will be capped at those provided in the list.
#   Setting this to true then reverting to false will not reset the values to their maximums as defined in the Reinforceable Blocks List.
# Default: false
accumulateReinforcementValues: false

## Whether or not TNT can damage reinforced blocks.
# Default: true
tntDamagesReinforcedBlocks: true

## Whether or not TNT entirely strips reinforcements or decrements them.
# Note: this option is ignored if tntDamagesReinforcedBlocks is set to false.
# Default: false
tntStripReinforcementEntirely: false

## Whether or not liquids can destroy reinforced blocks which can wash away (e.g. torches, railroad tracks).
# Default: true
liquidsDestroyReinforcedBlocks: true

## Whether or not physics-affected blocks (i.e. sand and gravel), if reinforced, are allowed to fall down.
# Note: if the blocks are allowed to fall, their reinforcement is simply removed, not transferred to their new location.
# Default: true
allowReinforcedBlockPhysics: true

## Whether or not fire can damage reinforced blocks.
# Note: if this is set to true, it is recommended to set extinguishReinforcementFire to true, otherwise fire will burn indefinitely and destroy enchantments quickly.
# Default: true
fireDamagesReinforcedBlocks: true

## Whether or not fires burning on reinforced blocks should occasionally extinguish, in order to prevent these blocks from being entirely ravaged by a fire.
# Default: true
extinguishReinforcementFire: true

## If extinguishReinforcementFire is set to true, this value determines the likelihood that a fire is to be extinguished.
# Note: This must be a value in the range 0.0-1.0, with a 1.0 being a 100% chance of extinguishing.
# Default: 0.9
extinguishChance: 0.9

## Whether or not pistons can move reinforced blocks.
# Default: true
pistonsMoveReinforcedBlocks: true

## Whether or not blocks should be allowed to "fade" while reinforced (e.g. snow melting, ice melting).
# Default: false
allowBlockFading: false

## Whether or not the creator of the reinforcement should be given a grace period to remove the reinforcement if it is in an undesirable location.
# Note: the item used in the reinforcement is not refunded.
# Default: true
allowReinforcementGracePeriod: true

## The amount of time the grace period should last to remove a reinforcement, if allowReinforcementGracePeriod is set to true.
# Note: must be an integer value greater than zero. The value is measured in seconds.
# Default: 3
gracePeriodTime: 3

## Whether or not reinforcements should "heal" to their maximum reinforcement after a period of time.
# Note: this does not mean the maximum reinforcement as described in the Reinforceable Blocks List, but rather the last highest reinforcement the block was raised to, prior to attack.
# Default: true
allowReinforcementHealing: true

## The amount of time before a block "heals" its reinforcement, if allowReinforcementHealing is set to true.
# Note: must be a value greater than zero. The value is measured in seconds.
# Default: 5
reinforcementHealTime: 5

## Whether or not a block remains in place when its RV reaches 0.
# Note: if this is set to true, when RV reaches 0, the reinforcement is simply removed. Otherwise, the block gets destroyed.
# Default: false
leaveBlockAfterDeinforce: false

## Whether or not mobs can change/damage reinforced blocks.
# Notes:
#   Setting this to false will mean sheep cannot eat reinforced grass.
#   Endermen will be unable to pickup reinforced blocks.
#   Withers will be unable to damage reinforced blocks.
# Default: false
mobsInteractWithReinforcedBlocks: false

## Whether or not the enderdragon can change/damage reinforced blocks.
# Default: false
enderdragonInteractWithReinforcedBlocks: false


#======== Advanced ========#

## Whether or not to integrate BlockSaver into Prism.
# Default: true
enableLogging: true


#======== Reinforcement Item List ========#

## A list of all the items which can be used to reinforce blocks, and their corresponding reinforcement values.
# Notes:
#   Setting a value of -2 will mean the reinforcement will automatically be the maximum value the block can take.
#   Any other value less than 1 is invalid.
#   If "accumulateReinforcementValues" is set to true, any material set here with a reinforcement value of -2 will not reinforce blocks.
reinforcementBlocks:
  OBSIDIAN: -2
  IRON_INGOT: 1
  GOLD_INGOT: 3
  DIAMOND: 10


#======== Reinforceable Blocks List ========#

## A list of all the items which can be reinforced by this plugin, and the maximum "reinforcement value" the block can reach, if accumulateReinforcementValues is set to false.
# (Note: Any value less than 1 is invalid)
reinforceableBlocks:
  ACTIVATOR_RAIL: 15
  ANVIL: 5
  BEACON: 10
  BIRCH_WOOD_STAIRS: 5
  BOOKSHELF: 10
  BREWING_STAND: 20
  BRICK: 10
  BRICK_STAIRS: 10
  BURNING_FURNACE: 5
  CACTUS: 3
  CAULDRON: 10
  CHEST: 5
  CLAY: 10
  COBBLE_WALL: 10
  COBBLESTONE: 10
  COBBLESTONE_STAIRS: 10
  DAYLIGHT_DETECTOR: 20
  DETECTOR_RAIL: 15
  DIAMOND_BLOCK: 5
  DIODE_BLOCK_OFF: 10
  DIODE_BLOCK_ON: 10
  DIRT: 10
  DISPENSER: 5
  DOUBLE_STEP: 10
  DROPPER: 5
  EMERALD_BLOCK: 5
  ENCHANTMENT_TABLE: 5
  ENDER_CHEST: 5
  ENDER_STONE: 7
  FENCE: 5
  FENCE_GATE: 5
  FLOWER_POT: 10
  FURNACE: 5
  GLASS: 10
  GLOWSTONE: 5
  GOLD_BLOCK: 7
  GRASS: 10
  HOPPER: 7
  ICE: 20
  IRON_BLOCK: 5
  IRON_DOOR: 3
  IRON_FENCE:
  JACK_O_LANTERN: 10
  JUKEBOX: 10
  JUNGLE_WOOD_STAIRS: 5
  LADDER: 5
  LAPIS_BLOCK: 7
  LEAVES: 10
  LEVER: 3
  LOG: 5
  MOB_SPAWNER: 10
  MOSSY_COBBLESTONE: 10
  MYCEL: 10
  NETHER_BRICK: 10
  NETHER_BRICK_STAIRS: 10
  NETHER_FENCE: 10
  NETHERRACK: 20
  NOTE_BLOCK: 10
  OBSIDIAN: 2
  PISTON_BASE: 5
  PISTON_STICKY_BASE: 5
  PISTON_EXTENSION: 5
  POWERED_RAIL: 15
  QUARTZ_BLOCK: 15
  QUARTZ_STAIRS: 15
  RAILS: 15
  REDSTONE_BLOCK: 7
  REDSTONE_COMPARATOR_OFF: 10
  REDSTONE_COMPARATOR_ON: 10
  REDSTONE_LAMP_OFF: 5
  REDSTONE_LAMP_ON: 5
  REDSTONE_TORCH_OFF: 10
  REDSTONE_TORCH_ON: 10
  REDSTONE_WIRE: 10
  SANDSTONE: 15
  SANDSTONE_STAIRS: 15
  SIGN: 10
  SIGN_POST: 10
  SMOOTH_BRICK: 10
  SMOOTH_STAIRS: 10
  SNOW_BLOCK: 10
  SOIL: 10
  SOUL_SAND: 10
  SPRUCE_WOOD_STAIRS: 5
  STEP: 10
  STONE: 10
  STONE_BUTTON: 3
  THIN_GLASS: 10
  TORCH: 10
  TRAP_DOOR: 3
  TRAPPED_CHEST:
  VINE: 10
  WALL_SIGN: 10
  WATER_LILY: 10
  WOOD: 5
  WOOD_BUTTON: 3
  WOOD_DOOR: 5
  WOOD_DOUBLE_STEP: 5
  WOOD_STAIRS: 5
  WOOD_STEP: 5
  WOOL: 10
  WORKBENCH: 5


#======== Tool Requirement List ========#

## A list of tools which can break certain blocks when reinforced. Used to prevent un-advanced players from easily destroying reinforcements.
# Notes:
#   Materials must use names as defined by the Bukkit Material class.
#   If a reinforceable block does not have any tools listed, it will be unbreakable by a player (but fire and TNT may still apply).
#   Write "ALL" in order to signify that the block may be broken by any tool or block, including a player's hands.
#   Write "HANDS" to signify that the block is breakable by a player's hands, in addition to any other tool listed.
toolRequirements:
  ACTIVATOR_RAIL: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  ANVIL: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  BIRCH_WOOD_STAIRS: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  BOOKSHELF: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  BREWING_STAND: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  BRICK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  BRICK_STAIRS: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  BURNING_FURNACE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  CAULDRON: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  CHEST: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  CLAY: IRON_SPADE,DIAMOND_SPADE,GOLD_SPADE
  COBBLE_WALL: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  COBBLESTONE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  COBBLESTONE_STAIRS: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  DAYLIGHT_DETECTOR: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  DETECTOR_RAIL: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  DIAMOND_BLOCK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  DIRT: IRON_SPADE,DIAMOND_SPADE,GOLD_SPADE
  DISPENSER: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  DOUBLE_STEP: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  DROPPER: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  EMERALD_BLOCK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  ENCHANTMENT_TABLE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  ENDER_CHEST: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  ENDER_STONE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  FENCE: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  FENCE_GATE: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  FURNACE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  GOLD_BLOCK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  GRASS: IRON_SHOVEL,DIAMOND_SHOVEL,GOLD_SHOVEL
  HOPPER: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  ICE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  IRON_BLOCK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  IRON_DOOR: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  IRON_FENCE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  JACK_O_LANTERN: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  JUKEBOX: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  JUNGLE_WOOD_STAIRS: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  LAPIS_BLOCK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  LOG: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  MOB_SPAWNER: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  MOSSY_COBBLESTONE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  MYCEL: IRON_SPADE,DIAMOND_SPADE,GOLD_SPADE
  NETHER_BRICK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  NETHER_BRICK_STAIRS: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  NETHER_FENCE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  NETHERRACK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  NOTE_BLOCK: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  OBSIDIAN: DIAMOND_PICKAXE
  POWERED_RAIL: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  QUARTZ_BLOCK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  QUARTZ_STAIRS: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  RAILS: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  REDSTONE_BLOCK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  SANDSTONE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  SANDSTONE_STAIRS: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  SIGN: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  SIGN_POST: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  SMOOTH_BRICK: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  SMOOTH_STAIRS: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  SNOW_BLOCK: IRON_SPADE,DIAMOND_SPADE,GOLD_SPADE
  SOIL: IRON_SPADE,DIAMOND_SPADE,GOLD_SPADE
  SOUL_SAND: IRON_SPADE,DIAMOND_SPADE,GOLD_SPADE
  SPRUCE_WOOD_STAIRS: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  STEP: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  STONE: IRON_PICKAXE,DIAMOND_PICKAXE,GOLD_PICKAXE
  TRAP_DOOR: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  TRAPPED_CHEST: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  WALL_SIGN: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  WOOD: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  WOOD_DOOR: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  WOOD_DOUBLE_STEP: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  WOOD_STAIRS: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  WOOD_STEP: IRON_AXE,DIAMOND_AXE,GOLD_AXE
  WORKBENCH: IRON_AXE,DIAMOND_AXE,GOLD_AXE
