#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
#  Configuration file for "BlockSaver". #
#  @author Nikita Pekin (Indivisible0)  #
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#


#======== Settings ==========#

reinforceableBlocks:
  GRASS: 10
  WOOD: 2
  STONE: 5
