#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
#  Configuration file for "BlockSaver". #
#  @author Nikita Pekin (Indivisible0)  #
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#


#======== Feedback ==========#

## Which feedback mode the plugin should use to represent damage being done to a reinforced block.
# Notes:
#   "visual" mode makes the plugin attempt to use color-changing particle effects (dependant on the health of the reinforcement).
#   "auditory" mode makes the plugin use auditory feedback (which changes based on the block's RV).
#   "off" mode uses the feedback defined below for damage events.
# Default: visual
primaryFeedback: visual

## The name of the effect to be played when a player fails to damage a reinforced block.
# Note: please use an effect contained within the Effect class.
# Default: EXTINGUISH
reinforcementDamageFailEffect: EXTINGUISH

## The name of the sound to be played when a player reinforces a block.
# Note: please use a sound contained within the Sound class.
# Default: ANVIL_USE
reinforceSuccessSound: ANVIL_USE

## The name of the sound to be played when a player fails to reinforce a block.
# Note: please use a sound contained within the Sound class.
# Default: BLAZE_HIT
reinforceFailSound: BLAZE_HIT

## The name of the sound to be played when a player fails to hit a reinforced block.
# Note: please use a sound contained within the Sound class.
# Default: CREEPER_DEATH
hitFailSound: CREEPER_DEATH


#======== Functionality ========#

## Whether or not TNT can damage reinforced blocks.
# Default: true
tntDamagesReinforcedBlocks: false

## Whether or not TNT entirely strips reinforcements or decrements them.
# Note: this option is ignored if tntDamagesReinforcedBlocks is set to false.
# Default: false
tntStripReinforcementEntirely: false

## Whether or not liquids can destroy reinforced blocks which can wash away (e.g. torches, railroad tracks).
# Default: true
liquidsDestroyReinforcedBlocks: false

## Whether or not physics-affected blocks (i.e. sand and gravel), if reinforced, are allowed to fall down.
# Note: if the blocks are allowed to fall, their reinforcement is simply removed, not transferred to their new location.
# Default: true
allowReinforcedBlockPhysics: true

## Whether or not fire can damage reinforced blocks.
# Note: if this is set to true, it is recommended to set extinguishReinforcementFire to true, otherwise fire will burn indefinitely and destroy enchantments quickly.
# Default: true
fireDamagesReinforcedBlocks: false

## Whether or not fires burning on reinforced blocks should occasionally extinguish, in order to prevent these blocks from being entirely ravaged by a fire.
# Default: true
extinguishReinforcementFire: false

## If extinguishReinforcementFire is set to true, this value determines the likelihood that a fire is to be extinguished.
# Note: This must be a value in the range 0.0-1.0, with a 1.0 being a 100% chance of extinguishing.
# Default: 0.9
extinguishChance: 0.9

## Whether or not pistons can move reinforced blocks.
# Default: true
pistonsMoveReinforcedBlocks: true

## Whether or not blocks should be allowed to "fade" while reinforced (e.g. snow melting, ice melting).
# Default: false
allowBlockFading: false

## The amount of time the grace period should last to remove a reinforcement, if allowReinforcementGracePeriod is set to true.
# Note: must be an integer value greater than zero. The value is measured in seconds.
# Default: 3
gracePeriodTime: 3

## Whether or not reinforcements should "heal" to their maximum reinforcement after a period of time.
# Note: this does not mean the maximum reinforcement as described in the Reinforceable Blocks List, but rather the last highest reinforcement the block was raised to, prior to attack.
# Default: true
allowReinforcementHealing: true

## The amount of time before a block "heals" its reinforcement, if allowReinforcementHealing is set to true.
# Note: must be a value greater than zero. The value is measured in seconds.
# Default: 5
reinforcementHealingTime: 12

## Whether or not a block remains in place when its RV reaches 0.
# Note: if this is set to true, when RV reaches 0, the reinforcement is simply removed. Otherwise, the block gets destroyed.
# Default: false
leaveBlockAfterDeinforce: false

## Whether or not mobs can change/damage reinforced blocks.
# Notes:
#   Setting this to false will mean sheep cannot eat reinforced grass.
#   Endermen will be unable to pickup reinforced blocks.
#   Withers will be unable to damage reinforced blocks.
# Default: false
mobsInteractWithReinforcedBlocks: false

## Whether or not the enderdragon can change/damage reinforced blocks.
# Default: false
enderdragonInteractWithReinforcedBlocks: false


#======== Worlds ========#

## List of worlds protected by BlockSaver.
worlds:
  - world
  - world_nether
  - world_the_end


#======== Advanced ========#

## Whether or not to log BlockSaver events into Prism.
# Default: true
prismLogging: true

## Whether or not to log BlockSaver events into Insight.
# Default: true
insightLogging: true

## Whether or not to integrate BlockSaver into WorldEdit.
# Default: true
integrateWorldEdit: true


#======== Reinforcement Item List ========#

## A list of all the items which can be used to reinforce blocks, and the number of times they may be used.
reinforcementBlocks:
  OBSIDIAN: 1


#======== Reinforceable Blocks List ========#

## A list of all the items which can be reinforced by this plugin, and the maximum "reinforcement value" the block can reach, if accumulateReinforcementValues is set to false.
# Note: Any value less than 1 is invalid
reinforceableBlocks:
  STONE: 15
  GRASS: 17
  DIRT: 17
  COBBLESTONE: 14
  WOOD: 14
  GOLD_ORE: 10
  IRON_ORE: 10
  COAL_ORE: 12
  LOG: 14
  LOG_2: 14
  LEAVES: 19
  LEAVES_2: 19
  SPONGE: 8
  GLASS: 11
  STAINED_GLASS: 11
  LAPIS_ORE: 10
  LAPIS_BLOCK: 10
  DISPENSER: 11
  SANDSTONE: 17
  NOTE_BLOCK: 17
  BED_BLOCK: 13
  POWERED_RAIL: 17
  DETECTOR_RAIL: 17
  PISTON_STICKY_BASE: 9
  WEB: 12
  PISTON_BASE: 9
  PISTON_EXTENSION: 9
  WOOL: 8
  PISTON_MOVING_PIECE: 9
  GOLD_BLOCK: 10
  IRON_BLOCK: 8
  DOUBLE_STEP: 14
  STEP: 14
  BRICK: 14
  BOOKSHELF: 15
  MOSSY_COBBLESTONE: 14
  OBSIDIAN: 2
  WOOD_STAIRS: 14
  CHEST: 13
  DIAMOND_ORE: 10
  DIAMOND_BLOCK: 8
  WORKBENCH: 13
  SOIL: 17
  FURNACE: 11
  BURNING_FURNACE: 11
  SIGN_POST: 16
  WOODEN_DOOR: 12
  LADDER: 10
  RAILS: 17
  COBBLESTONE_STAIRS: 14
  WALL_SIGN: 16
  LEVER: 9
  STONE_PLATE: 17
  IRON_DOOR_BLOCK: 10
  WOOD_PLATE: 17
  REDSTONE_ORE: 10
  GLOWING_REDSTONE_ORE: 10
  STONE_BUTTON: 9
  ICE: 17
  PACKED_ICE: 17
  SNOW_BLOCK: 19
  CACTUS: 10
  CLAY: 17
  JUKEBOX: 14
  FENCE: 14
  NETHERRACK: 19
  SOUL_SAND: 17
  GLOWSTONE: 11
  JACK_O_LANTERN: 16
  TRAP_DOOR: 12
  SMOOTH_BRICK: 15
  HUGE_MUSHROOM_1: 19
  HUGE_MUSHROOM_2: 19
  IRON_FENCE: 10
  THIN_GLASS: 11
  STAINED_GLASS_PANE: 11
  FENCE_GATE: 14
  BRICK_STAIRS: 14
  SMOOTH_STAIRS: 15
  MYCEL: 17
  NETHER_BRICK: 14
  NETHER_FENCE: 14
  NETHER_BRICK_STAIRS: 14
  ENCHANTMENT_TABLE: 10
  BREWING_STAND: 17
  CAULDRON: 14
  ENDER_STONE: 12
  REDSTONE_LAMP_OFF: 11
  REDSTONE_LAMP_ON: 11
  WOOD_DOUBLE_STEP: 14
  WOOD_STEP: 14
  SANDSTONE_STAIRS: 17
  EMERALD_ORE: 10
  ENDER_CHEST: 5
  EMERALD_BLOCK: 8
  SPRUCE_WOOD_STAIRS: 14
  BIRCH_WOOD_STAIRS: 14
  JUNGLE_WOOD_STAIRS: 14
  ACACIA_STAIRS: 14
  DARK_OAK_STAIRS: 14
  BEACON: 4
  COBBLE_WALL: 14
  WOOD_BUTTON: 9
  SKULL: 8
  ANVIL: 10
  TRAPPED_CHEST: 13
  GOLD_PLATE: 17
  IRON_PLATE: 17
  DAYLIGHT_DETECTOR: 19
  REDSTONE_BLOCK: 10
  QUARTZ_ORE: 12
  HOPPER: 12
  QUARTZ_BLOCK: 17
  QUARTZ_STAIRS: 17
  ACTIVATOR_RAIL: 17
  DROPPER: 11
  STAINED_CLAY: 15
  HAY_BLOCK: 9
  CARPET: 16
  HARD_CLAY: 15
  COAL_BLOCK: 10
  REDSTONE_WIRE: 20
  REDSTONE_TORCH_OFF: 20
  REDSTONE_TORCH_ON: 20
  DIODE_BLOCK_OFF: 20
  DIODE_BLOCK_ON: 20
  TRIPWIRE_HOOK: 20
  TRIPWIRE: 20
  REDSTONE_COMPARATOR_OFF: 20
  REDSTONE_COMPARATOR_ON: 20

#======== Tool Requirement List ========#

## A list of tools which can break certain blocks when reinforced. Used to prevent un-advanced players from easily destroying reinforcements.
# Notes:
#   Materials must use names as defined by the Bukkit Material class.
#   If a reinforceable block does not have any tools listed, it will be unbreakable by a player (but fire and TNT may still apply).
#   Write "ALL" in order to signify that the block may be broken by any tool or block, including a player's hands.
#   Write "HANDS" to signify that the block is breakable by a player's hands, in addition to any other tool listed.
toolRequirements:
  STONE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  GRASS: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  DIRT: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  COBBLESTONE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  WOOD: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  GOLD_ORE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  IRON_ORE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  COAL_ORE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  LOG: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  LOG_2: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  LEAVES: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  LEAVES_2: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  SPONGE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  GLASS: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  STAINED_GLASS: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  LAPIS_ORE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  LAPIS_BLOCK: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  DISPENSER: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  SANDSTONE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  NOTE_BLOCK: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  BED_BLOCK: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  POWERED_RAIL: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  DETECTOR_RAIL: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  PISTON_STICKY_BASE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  WEB: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  PISTON_BASE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  PISTON_EXTENSION: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  WOOL: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  PISTON_MOVING_PIECE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  GOLD_BLOCK: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  IRON_BLOCK: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  DOUBLE_STEP: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  STEP: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  BRICK: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  BOOKSHELF: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  MOSSY_COBBLESTONE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  OBSIDIAN: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  WOOD_STAIRS: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  CHEST: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  DIAMOND_ORE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  DIAMOND_BLOCK: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  WORKBENCH: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  SOIL: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  FURNACE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  BURNING_FURNACE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  SIGN_POST: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  WOODEN_DOOR: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  LADDER: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  RAILS: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  COBBLESTONE_STAIRS: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  WALL_SIGN: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  LEVER: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  STONE_PLATE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  IRON_DOOR_BLOCK: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  WOOD_PLATE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  REDSTONE_ORE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  GLOWING_REDSTONE_ORE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  STONE_BUTTON: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  ICE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  PACKED_ICE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  SNOW_BLOCK: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  CACTUS: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  CLAY: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  JUKEBOX: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  FENCE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  NETHERRACK: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  SOUL_SAND: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  GLOWSTONE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  JACK_O_LANTERN: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  TRAP_DOOR: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  SMOOTH_BRICK: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  HUGE_MUSHROOM_1: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  HUGE_MUSHROOM_2: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  IRON_FENCE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  THIN_GLASS: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  STAINED_GLASS_PANE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  FENCE_GATE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  BRICK_STAIRS: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  SMOOTH_STAIRS: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  MYCEL: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  NETHER_BRICK: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  NETHER_FENCE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  NETHER_BRICK_STAIRS: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  ENCHANTMENT_TABLE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  BREWING_STAND: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  CAULDRON: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  ENDER_STONE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  REDSTONE_LAMP_OFF: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  REDSTONE_LAMP_ON: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  WOOD_DOUBLE_STEP: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  WOOD_STEP: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  SANDSTONE_STAIRS: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  EMERALD_ORE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  ENDER_CHEST: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  EMERALD_BLOCK: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  SPRUCE_WOOD_STAIRS: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  BIRCH_WOOD_STAIRS: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  JUNGLE_WOOD_STAIRS: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  ACACIA_STAIRS: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  DARK_OAK_STAIRS: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  BEACON: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  COBBLE_WALL: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  WOOD_BUTTON: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  SKULL: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  ANVIL: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  TRAPPED_CHEST: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  GOLD_PLATE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  IRON_PLATE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  DAYLIGHT_DETECTOR: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  REDSTONE_BLOCK: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  QUARTZ_ORE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  HOPPER: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  QUARTZ_BLOCK: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  QUARTZ_STAIRS: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  ACTIVATOR_RAIL: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  DROPPER: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  STAINED_CLAY: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  HAY_BLOCK: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  CARPET: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  HARD_CLAY: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  COAL_BLOCK: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  REDSTONE_WIRE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  REDSTONE_TORCH_OFF: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  REDSTONE_TORCH_ON: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  DIODE_BLOCK_OFF: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  DIODE_BLOCK_ON: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  TRIPWIRE_HOOK: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  TRIPWIRE: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  REDSTONE_COMPARATOR_OFF: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
  REDSTONE_COMPARATOR_ON: DIAMOND_PICKAXE,DIAMOND_SPADE,DIAMOND_AXE,DIAMOND_SWORD
