name: BlockSaver
main: in.nikitapek.blocksaver.BlockSaverPlugin
load: POSTWORLD
version: ${project.version}
author: Indiv0
description: A plugin for providing block protection capabilities on a server.
depend: [ProtocolLib]

commands:
  blocksaver:
    description: Controls all functions of the BlockSaver plugin.
    usage: |
      /<command> [feedback]
      Example: /<command> feedback - Toggles whether or not a player should recieve written feedback for various reinforcement events.
    permission: blocksaver.blocksaver
    permission-message: Sorry, you don't have permission to use BlockSaver.

permissions:
  blocksaver.*:
    description: Controls all BlockSaver permissions
    children:
      blocksaver.blocksaver: true
      blocksaver.feedback: true
