name: BlockSaver
main: in.nikitapek.blocksaver.BlockSaverPlugin
load: POSTWORLD
version: ${project.version}
author: Indiv0
description: A plugin for providing block protection capabilities on a server.
softdepend: [Prism, WorldEdit]
dev-url: http://github.com/Indiv0/block-saver/

commands:
  blocksaver:
    description: Controls all functions of the BlockSaver plugin.
    usage: |
      /<command> feedback - Toggles feedback in chat
      /<command> autoenforce - Toggles auto-reinforcement mode
      /<command> reinforce - Reinforces the WorldEdit selection

permissions:
  blocksaver.blocksaver.autoenforce:
    children:
      blocksaver.blocksaver: true
  blocksaver.blocksaver.feedback:
    children:
      blocksaver.blocksaver: true
  blocksaver.blocksaver.worldedit:
    children:
      blocksaver.blocksaver: true
  blocksaver.reinforce:
    description: Allows the reinforcement of blocks
  blocksaver.damage:
    description: Allows the player to damage reinforced blocks
  blocksaver.exempt:
    description: The player may break reinforced blocks as if they were not reinforced
  blocksaver.feedback:
    description: Controls what feedback the player receives
  blocksaver.feedback.reinforce.success:
    description: Feedback for a successful reinforcement
  blocksaver.feedback.reinforce.fail:
    description: Feedback for a failed reinforcement
  blocksaver.feedback.damage.success:
    description: Feedback for a successful reinforcement damage
  blocksaver.feedback.damage.fail:
    description: Feedback for a failed reinforcement damage
  blocksaver.feedback.hit:
    description: Feedback for an improper tool use
  blocksaver.feedback.permissions:
    description: Feedback for insufficient permissions
