name: BlockSaver
main: in.nikitapek.blocksaver.BlockSaverPlugin
load: POSTWORLD
version: ${project.version}
author: Indiv0
description: A plugin for providing block protection capabilities on a server.
softdepend: [Prism]
dev-url: http://github.com/Indiv0/block-saver/

commands:
  blocksaver:
    description: Controls all functions of the BlockSaver plugin.
    usage: |
      /<command> feedback [true|false] - Toggles feedback in chat

permissions:
  blocksaver.blocksaver.feedback:
    children:
      blocksaver.blocksaver: true